cabal-version:      3.14
name:               example-api

version:            0.1.0.0

license:            BSD-3-Clause
license-file:       LICENSE

author:             Stephen Onnen
maintainer:         stephen.onnen@gmail.com

build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    -- exposed-modules:  -- you'll fill these in as you create modules
    build-depends:    base ^>=4.22.0.0
    hs-source-dirs:   src
    default-language: GHC2024

executable example-api
    import:           warnings
    main-is:          Main.hs
    -- other-modules:
    build-depends:
        base ^>=4.22.0.0
        , example-api
        , scotty
        , sqlite-simple
        , aeson
        , text
        , bytestring
        , wai
    hs-source-dirs:   app
    default-language: GHC2024

executable example-api-worker
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base ^>=4.22.0.0
        , example-api
        , sqlite-simple
        , async
        , text
    hs-source-dirs:   worker
    default-language: GHC2024