cabal-version:   3.8
name:            example-api
version:         0.1.0.0
license:         BSD-3-Clause
license-file:    LICENSE
author:          Stephen Onnen
maintainer:      stephen.onnen@gmail.com
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options: -Wall -threaded

common defaults
  import:             warnings
  build-depends:      base ^>=4.19.2.0
  default-language:   GHC2021
  default-extensions: OverloadedStrings

library
  import:         defaults

  -- exposed-modules:  -- you'll fill these in as you create modules
  hs-source-dirs: src

executable example-api
  import:         defaults
  main-is:        Main.hs
  build-depends:
    , aeson
    , bytestring
    , example-api
    , scotty
    , sqlite-simple
    , text
    , wai

  hs-source-dirs: app

executable example-api-worker
  import:         defaults
  main-is:        Main.hs
  build-depends:
    , async
    , example-api
    , sqlite-simple
    , text

  hs-source-dirs: worker
