(lang dune 3.23)

(name example_api)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name example_api)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml dream sqlite3 lwt lwt_ppx eio eio_main yojson)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
