(lang dune 3.23)

(name example_api)

(source
 (github username/reponame))

(authors "Stephen Onnen <stephen.onnen@gmail.com>")

(maintainers "Stephen Onnen <stephen.onnen@gmail.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name example_api)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml dream sqlite3 lwt lwt_ppx eio yojson ptime)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
